apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: lsc-knative-trigger-func
spec:
  broker: lsc-knative-broker
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: python-test-events