apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: lsc-knative-trigger
spec:
  broker: lsc-knative-broker
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: display-target